// Countries supported by Webshare proxy service
import type { CountryInfo } from '@/types/types';

// All available countries supported by Webshare (only countries with actual working proxies)
export const ALL_COUNTRIES: CountryInfo[] = [
  {
    code: 'US',
    name: 'United States',
    region: 'North America',
    continent: 'North America',
    supported: true,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'DE',
    name: 'Germany',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'ES',
    name: 'Spain',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'FR',
    name: 'France',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'CA',
    name: 'Canada',
    region: 'North America',
    continent: 'North America',
    supported: true,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'IT',
    name: 'Italy',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'AU',
    name: 'Australia',
    region: 'Oceania',
    continent: 'Oceania',
    supported: true,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'PL',
    name: 'Poland',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'RO',
    name: 'Romania',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'BR',
    name: 'Brazil',
    region: 'South America',
    continent: 'South America',
    supported: true,
  },
  {
    code: 'SE',
    name: 'Sweden',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'SG',
    name: 'Singapore',
    region: 'Asia',
    continent: 'Asia',
    supported: true,
  },
  {
    code: 'DK',
    name: 'Denmark',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'JP',
    name: 'Japan',
    region: 'Asia',
    continent: 'Asia',
    supported: true,
  },
  {
    code: 'LT',
    name: 'Lithuania',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'HU',
    name: 'Hungary',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'AT',
    name: 'Austria',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'NO',
    name: 'Norway',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'CZ',
    name: 'Czechia',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'RS',
    name: 'Serbia',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    region: 'Africa',
    continent: 'Africa',
    supported: true,
  },
  {
    code: 'MX',
    name: 'Mexico',
    region: 'North America',
    continent: 'North America',
    supported: true,
  },
  {
    code: 'BE',
    name: 'Belgium',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'LV',
    name: 'Latvia',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'CY',
    name: 'Cyprus',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'SI',
    name: 'Slovenia',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'CL',
    name: 'Chile',
    region: 'South America',
    continent: 'South America',
    supported: true,
  },
  {
    code: 'AR',
    name: 'Argentina',
    region: 'South America',
    continent: 'South America',
    supported: true,
  },
  {
    code: 'MT',
    name: 'Malta',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'EE',
    name: 'Estonia',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'GR',
    name: 'Greece',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'FI',
    name: 'Finland',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'TR',
    name: 'Türkiye',
    region: 'Asia',
    continent: 'Asia',
    supported: true,
  }, // Türkiye = Turkey (code: TR)
  {
    code: 'AL',
    name: 'Albania',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'EG',
    name: 'Egypt',
    region: 'Africa',
    continent: 'Africa',
    supported: true,
  },
  {
    code: 'UA',
    name: 'Ukraine',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'PT',
    name: 'Portugal',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'IE',
    name: 'Ireland',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    region: 'Europe',
    continent: 'Europe',
    supported: true,
  },
];

// Get country by code (used by other modules)
export function getCountryByCode(code: string): CountryInfo | undefined {
  return ALL_COUNTRIES.find(country => country.code === code);
}
